### ISSUE TITLE
How to set scrollbar on bottom of Y axis in initial loading?

### ISSUE THREAD

**Issue by ajithasayone** [mdbootstrap/perfect-scrollbar#156]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/mdbootstrap/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/mdbootstrap/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [ ] Provide a page or source code where the issue can be checked

**Comment by JulioAgopian** [comment]
Hello  could you explain how you achieved this ? :D
