### ISSUE TITLE
PS bug in mobile ([Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.)

### ISSUE THREAD

**Issue by amiranagram** [mdbootstrap/perfect-scrollbar#41]
Hello,

I am having this issue with perfect scrollbar only on mobile. I guess the bug appears only on touch event. When scrolling the bar I get this error in console:

```
perfect-scrollbar.esm.js?b7f5:562
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
```

And this is the line where it cannot prevent default:

```
function mouseMoveHandler(e) {
    if (e.touches && e.touches[0]) {
      e[pageY] = e.touches[0].pageY;
    }
    element[scrollTop] =
      startingScrollTop + scrollBy * (e[pageY] - startingMousePageY);
    addScrollingClass(i, y);
    updateGeometry(i);

    e.stopPropagation();
    e.preventDefault(); // Here
  }
```

Steps to reproduce:

1. Check my fiddle: [https://jsfiddle.net/671duorb/1/](https://jsfiddle.net/671duorb/1/)
2. Open Console (F12)
3. Toggle device toolbar
4. Select one of the mobile screens
5. Try to drag the scrollbar (not screen, the bar itself)

In jsfiddle console nothing will appear, but in your browsers console you will get the above mentioned error. After that the scrollbar gets stuck in focused state until refresh.

**Comment by thiagoteberga** [comment]
Has the problem been solved? I have the same problem.

**Comment by amiranagram** [comment]
I changed 3 jobs and 4 frameworks, I don't care anymore.

**Comment by lenamtl** [comment]
What is the fix for the latest perfect-scrollbar version?
Any Pull or gist ?
