### ISSUE TITLE
Problem initializing PS with a not yet DOM inserted container (regression compared to 0.8.1)

### ISSUE THREAD

**Issue by salmonb** [mdbootstrap/perfect-scrollbar#715]
hi,

My UI is fully generated from JavaScript and I need to initialize PS on containers before they are inserted into DOM. I had no problem with PS version <= 0.8.1, but since I moved to 1.2.0, I noticed some initialization problems such as the vertical scrollbar being on the left instead of the right.

After some investigation, it seems this is because of some PS initialization code such as:

```
var railYStyle = get(this.scrollbarYRail); // Same as getComputedStyle(this.scrollbarYRail)
this.scrollbarYRight = parseInt(railYStyle.right, 10);
if (isNaN(this.scrollbarYRight)) {
    this.isScrollbarYUsingRight = false;
    this.scrollbarYLeft = toInt(railYStyle.left);
} else {
    this.isScrollbarYUsingRight = true;
}
```
getComputedStyle() leaves most of fields empty if called before the container is inserted into DOM so isNaN(this.scrollbarYRight) returns true.

Could that be fixed so PS can correctly work when containers are inserted into DOM after PS initialization?

Thank you!

**Comment by rickyale** [comment]
I had a similar problem, for me it was fixed with an update() on the next tick of page rendering, not pretty but it may resolve problems related do the computed style.   

`setTimeout(() => { this.ps.update(); }, 1);`

Also you can set the visibility hidden and then make it visible after the update().
