### ISSUE TITLE
Update after window resize

### ISSUE THREAD

**Issue by Costegillio** [mdbootstrap/perfect-scrollbar#740]
Greetings!

After window resize, scrollbar updates its position and size only after i scrolled. I'd like to update it immediately after window resize, how can i get that?

That method doesn't work, its still updates only after i scrolled:
`
ps = new PerfectScrollbar("#mainWrapper");
$(window).resize(function() {ps();});`

Thank for attention.

**Comment by utatti** [comment]
You should call `ps.update()` instead of `ps()`.

**Comment by Costegillio** [comment]
@utatti, thanks for your reply. 

Actually i did it right as you say, just gave wrong example.
Here is full code and it doesn't work:
`
f(device.desktop()===true){

     psB = new PerfectScrollbar("#mainWrapper", {suppressScrollX:true});
     psF = new PerfectScrollbar("#frames", {suppressScrollX:true});
					
     $(window).resize(function() {
	psB.update();
	psF.update();
     });

}`

**Comment by utatti** [comment]
It seems they should work. Can I have a working example or fiddle online?

**Comment by GufNZ** [comment]
Try moving the updated calls inside a `setTimeout` or `requestAnimationFrame` callback to give things time to re-render at the new size first perhaps?

**Comment by DmitryTezh** [comment]
I have the same issue, ps.update() not works, only ps.destroy() and re-creating helps me

**Comment by DmitryTezh** [comment]
Do you have any ideas?
