### ISSUE TITLE
Disable vertical scroll override

### ISSUE THREAD

**Issue by meinhard-meintjes** [mdbootstrap/perfect-scrollbar#749]
Hi,

This plugin is cool and i'm using it for a project of ours where we have a Netflix-style horizontal scroller.
It does work, but one issue remains that is a bit of a pain:

When i'm scrolling normally (vertically) through the page and reach that (full-width) horizontal scroller, the normal scrolling stops as your plugin is reading/overriding the scroll event. But I only need the X-scrolling, so I was wondering if it's possible to have a setting that totally ignores y-scrolling on your side?

This is the website: https://goo.gl/JEVsux

Thanks!

**Comment by jowhannez** [comment]
Sent you a mail asking for help since it seems like you fixed the issue and here's the reply:

> Hi Johannes,
>
>It seems that it might have been magically "fixed" by a browser update. 
>I suspect it might have been a browser issue then.
>Perhaps the problem was only on Safari - can't really remember!
>Actually, just checked it on microsoft edge, and there the problem still remains :(
>
>Anyway, at one point I added these options:
>
>    suppressScrollY: true,
>    wheelPropagation: true
>
>Maybe that helps to get it working on firefox and chrome at least.

Adding these as [config]="{suppressScrollY: true, wheelPropagation: true}" on the angular component fixed it for me in chromium at least!
