### ISSUE TITLE
Relax ctrl+scroll event to allow zooming

### ISSUE THREAD

**Issue by sambaptista** [mdbootstrap/perfect-scrollbar#753]
This report its more about the behavior than a real bug (I think).

On Windows and linux ctrl+mousewheel doesn't affect the scroll (whether there is scrollable content or not).

When perfect-scrollbar the page is zoomable if there is no scrollable content, but as soon as there is overflow and the scroll is required, the zoom doesn't work anymore. Its different from the native behavior.

From what I see, ctrl+mousewheel should never affect the scroll, but I may be forgetting some use cases. 

Is it a feature ? a bug ? or a negligence ? Optionally is there any config to reproduce the native behavior ?

**Comment by GufNZ** [comment]
It sounds like PS needs a modifier check in the event handler(s)...
