### ISSUE TITLE
Feature Request: Init only if browser has visible scrollbars

### ISSUE THREAD

**Issue by CinKon** [mdbootstrap/perfect-scrollbar#771]
Hi, 

I'd have a feature request: Would it be possible, to initialize the scrollbar only if the browser has visible scrollbars (unlike mobile browsers/macOS browsers). 
In my project I check this myself, and prevent the initialization of perfect-scrollbar, if the browser has no visible scrollbar on its own, but another plugin I use (https://github.com/Degfy/vue-perfect-scrollbar) is just a Vue-Wrapper and would need that option native by perfect-scrollbar.

**Comment by seyfer** [comment]
Actually, it can be achieved by overloading the library classes. Play with `opacity` property.
