### ISSUE TITLE
Unable to use NPM Package in Laravel Mix (Laravel v5.5)

### ISSUE THREAD

**Issue by kobadg** [mdbootstrap/perfect-scrollbar#772]
I am able to include the package in Laravel using NPM, and the mix task runs successfully, however when trying to initialize it in a site, I get an error as if the PerfectScrollbar function does not exist. (I'll get the exact error if needed, but ideally it's saying it just can't find the function.)

**Comment by lichnow** [comment]
`yarn add jquery.nicescroll`,
`require('jquery.nicescroll')`,
`$(function () {
        $("body").niceScroll({
            scrollspeed: 160,
            mousescrollstep: 140,
            cursorcolor: '#eee',
            cursorborder: 'none',
            cursorborderradius: '7px',
            cursorwidth: '3px',
            cursoropacitymax: 0.6
        });
    })`
