### ISSUE TITLE
Can she achieve scrollbottom?（能实现scrollbottom的操作吗？）

### ISSUE THREAD

**Issue by max-level** [mdbootstrap/perfect-scrollbar#794]
ex:el.scrollTop = el.scrollHeight has a bug!
**The last one does not show up and requires mouse scrolling！！！**
（最后一个显示不出来，需要鼠标滚动）

**Comment by ffey** [comment]
我使用的时候没有问题，你要把你使用的代码粘贴出来才可以看到是什么问题

**Comment by ffey** [comment]
我觉得是滚动到最后的操作发生在你添加的动作之前了，试试setTimeout吧
