### ISSUE TITLE
Bug in mouse wheel event child consumption check

### ISSUE THREAD

**Issue by sconix** [mdbootstrap/perfect-scrollbar#803]
We run into problem where we have a horizontally scrollable element inside a vertically scrollable perfect-scrollbar container where the perfect-scrollbar won't scroll if trying to use the wheel vertically inside the horizontally scrollable container.

I checked the code and found a bug in the wheel shouldBeConsumedByChild function. The if scrollable checks are missing a check that there is actually scrolling (delta) to the direction it checks.

So this:
`
          if (
            !(cursor.scrollLeft === 0 && deltaX < 0) &&
            !(cursor.scrollLeft === maxScrollLeft && deltaX > 0)
          ) {
`

should be:
`          if (deltaX &&
            !(cursor.scrollLeft === 0 && deltaX < 0) &&
            !(cursor.scrollLeft === maxScrollLeft && deltaX > 0)
          ) {
`

And the same treatment for the Y check with deltaY naturally.  At least this change fixes our problem and I guess there is no point of marking event for the child if there actually was no scrolling in the direction that is scrollable.

**Comment by airwin** [comment]
good job, but I think it should be `deltaX != 0`

**Comment by sconix** [comment]
I believe that would work also, but my suggestions should cover "error" cases as well (not sure if such cases are possible though). So not sure which one is better, but anyway would love to see this fixed soon.

**Comment by MichaelTamm** [comment]
We ran into the exact same problem.
I put together a little [CodeSandbox example](https://codesandbox.io/s/jjnrnrkwq3) which reproduces the issue.
