### ISSUE TITLE
Cannot read property 'scrollTop' of null

### ISSUE THREAD

**Issue by malinduDeAlwis90** [mdbootstrap/perfect-scrollbar#834]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [x] Provide a page or source code where the issue can be checked

**Comment by apriljunge** [comment]
Please close this in favor of #835
