### ISSUE TITLE
different browser scroll problem

### ISSUE THREAD

**Issue by pcodedviral** [mdbootstrap/perfect-scrollbar#844]
hello sir,

I am using windows 10 with Mozilla Firefox browser 64.0.2 (64-bit)[ lettest ]
in this browser, the scroll will attempt very slow compared to google chrome and Microsoft edge,

can you give me a proper solution for firefox browser,

in your live link, the problem will still there

[https://utatti.github.io/perfect-scrollbar/](https://utatti.github.io/perfect-scrollbar/)

thanks,
Mr. Viral Dhimmar

**Comment by MartDSam** [comment]
Did you solve this?

I have the same problem.

**Comment by pcodedviral** [comment]
No it's not solved
