### ISSUE TITLE
I have some code to show you. 

### ISSUE THREAD

**Issue by boseakash7** [mdbootstrap/perfect-scrollbar#846]
I like perfect scrollbar but the only feature that I find missing is smooth scroll. So I am making some changes to the perfect scrollbar to enable the smooth scrolling and also I need this for a project of mine.

Can you guys please check the code if you guys like it or not?
Here is the link: https://drive.google.com/open?id=1q7Slt5kMf-t2n8DIwHLqwxVar1Qdhh5Y

Thank you. 
P.S. Sorry for my english.
P.P.S I am not a good programmer, I am just trying.

**Comment by oli-mo** [comment]
Hey there,
you might do a pull request instead of linking a zip file?
That would be helpful, thx.

**Comment by mattonit** [comment]
@boseakash7 thank you for contributing to Perfect Scrollbar. Unfortunately, we can't review your changes unless you'll make us a PR. This is the official (and only) way for your code to be added to this project.
