### ISSUE TITLE
PROJECT ABANDONED?

### ISSUE THREAD

**Issue by tomasdev** [mdbootstrap/perfect-scrollbar#847]
Doesn't seem like the owner is doing anything. 19 open PRs.

**Comment by DanielRuf** [comment]
Bump. What is the current status of this project?

**Comment by madprops** [comment]
Any good alternative?

**Comment by mattonit** [comment]
@tomasdev @DanielRuf, some time ago the original creator of PS has abandoned the project. We (@mdbootstrap) have taken over this repo and npm package and we have plans to maintain this library as we (and I personally) find the potential of this project
