### ISSUE TITLE
right margin cropped

### ISSUE THREAD

**Issue by NorthwooDzp** [mdbootstrap/perfect-scrollbar#853]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [x] Provide a page or source code where the issue can be checked
https://jsfiddle.net/L1zjrv2k/

I added margin 50px. to content. left, top and bottom margins displayed propertly. where is right margin?

**Comment by apriljunge** [comment]
@NorthwooDzp This is not an issue with perfect scrollbar. Just the expected behaviour of your browser. If you remove perfect scrollbar in your example you can see it very clear.

You could try setting a padding instead.
