### ISSUE TITLE
Auto-Scroll while dragging an item

### ISSUE THREAD

**Issue by hfalucas** [mdbootstrap/perfect-scrollbar#859]
Is it possible to make perfect-scrollbar automatically scroll up/down while dragging an item in the edge its container?

To reproduce my use case try to drag the `Item 1` to the end of the list (after `Item 8`):
[Here's the jsfiddle](https://jsfiddle.net/hfalucas/rq3v9uxf/12/)

<hr>

- [x] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [x] Provide a page or source code where the issue can be checked

**Comment by lean1024** [comment]
https://www.npmjs.com/package/react-beautiful-dnd
you can use react-beautiful dnd, which got a autoscroll functionality. 
![image](https://user-images.githubusercontent.com/32680721/61138276-7af78600-a4c7-11e9-910b-7316a1179304.png)
