### ISSUE TITLE
textarea scrollbar is not visible if placed inside perfect-scrollbar container on IE10

### ISSUE THREAD

**Issue by sosharma1403** [mdbootstrap/perfect-scrollbar#861]
Steps to reproduce:
1. create a perfect scrollbar container
2. add textarea in the container

Browser: Internet explorer, Edge

Fiddle link: https://jsfiddle.net/d7uw169p/3/

**Comment by apriljunge** [comment]
As [mentioned in the Readme](https://github.com/mdbootstrap/perfect-scrollbar#ie-support) IE 10 is not supported by perfect-scrollbar

**Comment by sosharma1403** [comment]
Hi @apriljunge this is also reproducible with IE and Edge latest version.

**Comment by apriljunge** [comment]
I cant reproduce it. Neither in IE nor in Edge. Im on Windows 10.
![textarea-in-edge](https://user-images.githubusercontent.com/10660618/58549427-c4d42780-820b-11e9-8d15-1e3b47005c1d.png)

**Comment by mattonit** [comment]
@sosharma1403 could you please record a screencast where the issue will be shown? I can't reproduce it either
