### ISSUE TITLE
How to use arrows/buttons instead of a scrollbar?

### ISSUE THREAD

**Issue by stratboy** [mdbootstrap/perfect-scrollbar#866]
Hi, not a real issue, just a question and maybe a feature request.

I need arrows instead of a scrollbar. Please see attachment. 

So:

- Can I safely hide the scrollbar?
- Can I attack some perfect-scrollbar scroll function to the buttons mouse events?

How would you do it (if possible)?

Thank you, regards
![Schermata 2019-05-13 alle 16 14 19](https://user-images.githubusercontent.com/437598/57628431-32d8e780-759a-11e9-860a-9b6513082e72.png)

**Comment by stratboy** [comment]
No answers after 10 days means no tech support means wrong script to adopt in production environment.

**Comment by mccoolaustinm** [comment]
Yes and yes, to both of your questions. This scrollbar wraps existing native offset properties on the element it's assigned to. 

You don't need this library to accomplish your goal and it really does nothing for your use case. Those are native scrolling features. This library adds an attractive scrollbar, and you're not looking for a pre-made scrollbar, but rather a combination of buttons. You need a custom solution based on native scrolling, and that isn't too hard.
