### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by utatti** [mdbootstrap/perfect-scrollbar#869]
If anybody want to maintain this project, please comment below. I'll transfer the ownership of this repository and [the npm package](https://www.npmjs.com/package/perfect-scrollbar) (please let me know your npm account too).

**Comment by IlCallo** [comment]
No volunteering (yet), but **please** make sure the new maintainer isn't malicious, before transfering ownership...
A number of projects rely on this dependency and we don't want to get a second [event-stream vulnerability](https://ardalis.com/the-javascript-npm-event-stream-vulnerability) in the wild, don't we? :)

I'll talk to my company and check if we can afford to invest some working days to maintain this package ourselves

**Comment by utatti** [comment]
@IlCallo Thanks for your advice. You're absolutely right. I'll try my best to ensure that the new maintainer isn't malicious.

**Comment by filipkappa** [comment]
Hello!
I've contacted the rest of the team from [MDB ](https://github.com/mdbootstrap/bootstrap-material-design) and we would be happy to continue maintaining the project :)
We've got both people and resources at the moment so it would be a "perfect" project for us. Please contact me directly at f.kapusta@mdbootstrap.com if you need any details :)
Our NMP: https://www.npmjs.com/~mdbootstrap

**Comment by utatti** [comment]
@filipkappa 

Great to hear that! May I transfer the ownership to you or @mdbootstrap?

**Comment by filipkappa** [comment]
Please transfer directly to @mdbootstrap ;)

**Comment by utatti** [comment]
@filipkappa Thanks! I've sent the transfer request in GitHub. I've also transfered npm package, so please check it out.

**Comment by utatti** [comment]
Thanks guys!
