### ISSUE TITLE
element-ui中集成滚动，出现原生滚动并存的状态

### ISSUE THREAD

**Issue by 1269894710** [mdbootstrap/perfect-scrollbar#870]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [ ] Provide a page or source code where the issue can be checked

**Comment by 1269894710** [comment]
![TIM图片20190520161949](https://user-images.githubusercontent.com/42958636/58006656-25cc7300-7b1b-11e9-93c7-fc41cfb47d54.png)

**Comment by apriljunge** [comment]
@1269894710 Can you please provide a JSFiddle or Codepen where we can see this behaviour?

**Comment by evolmk** [comment]
you most likely have Scrolling css class applied to your table.
