### ISSUE TITLE
滚动条置于底部不起作用

### ISSUE THREAD

**Issue by weiweishiyi** [mdbootstrap/perfect-scrollbar#875]
Make sure these boxes are checked before submitting your issue -- thank you!
我们是列表切换因为向上滚动加载，滚动条置于底部，已经设置了
box.scrollTop = box.scrollHeight+20;；但是首次加载的时候没有置于底部还需要手动滚动一下；并且已经打印了box.scrollHeight - box.scrollTop === box.clientHeight为true，但是仍然没有置于底部。麻烦指导一下
- [ ] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [ ] Provide a page or source code where the issue can be checked

**Comment by mattonit** [comment]
To let others understand your issue, this should be written in English.
