### ISSUE TITLE
Option to show horizontal scrollbar on top of div?

### ISSUE THREAD

**Issue by adalenv** [mdbootstrap/perfect-scrollbar#880]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/utatti/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/utatti/perfect-scrollbar/wiki/Caveats)
- [x] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [ ] Provide a page or source code where the issue can be checked

**Comment by davi9091** [comment]
You can change position of the horizontal scrollbar by simply changing position of the element with the `ps__rail-x` class. 

For this specific case: 
```
.ps__rail-x {
  bottom: auto;
  top: 0px;
}
```

[JSFiddle](https://jsfiddle.net/kcd45n3j/)
