### ISSUE TITLE
Error Webpack + PerfectScrollbar

### ISSUE THREAD

**Issue by EdoardoLopez** [mdbootstrap/perfect-scrollbar#881]
I'm try use this plugn with webpack but i get the error "PerfectScrollbar is not a constructor".

I try use PerfectScrollbar like a ProvidePlugin in webpack

this is a demo https://github.com/EdoardoLopez/WebpackPerfectScrollbar.git

**Comment by Petercopter** [comment]
@EdoardoLopez Try this:
```
PerfectScrollbar: ['perfect-scrollbar', 'default']
```
In your Webpack config

**Comment by EdoardoLopez** [comment]
@Petercopter  thanks!
