### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by mattlewis92** [mdbootstrap/perfect-scrollbar#887]
Hi there,

There's been lots of fixes merged to the master of the github repo that aren't published to npm yet, any chance someone could publish a new version there? 

Thanks! 😄

**Comment by z3rog** [comment]
> someone could publish a new version there?
+1 🤭

**Comment by mattonit** [comment]
This will be done soon. I'm gonna fix some critical issues and then I'll publish a new version to GitHub and NPM
