### ISSUE TITLE
Not reduced scroll field (Angular)

### ISSUE THREAD

**Issue by ilya17** [mdbootstrap/perfect-scrollbar#890]
Hi all! I have a problem with scrolling when deleting an element, the block does not narrow, although a different behavior was expected. I have a little development experience, but I did not find a similar problem. 
I think that this is somehow connected with the scroll bar, it does not decrease in size, which prevents the block from decreasing. If I hide the scrollbar (.ps__rail-y {display: none !important;}), then the problem goes away, but I need a scroll.

Parent Styles: position: absolute;
Container style with Perfect Scrollbar: position: relative; max-height: 350px; margin: 8px; overflow: auto;

Video:

https://drive.google.com/open?id=1PudTT8fsHk2RO1BFAvb-frgHWEmhNdnu

**Comment by ilya17** [comment]
If I scroll down to the level of an empty field, it then disappears.

**Comment by mattonit** [comment]
We can't access the video and we can't reproduce your issue
