### ISSUE TITLE
1.5.0 breaks the design of ngx-perfect-scrollbar

### ISSUE THREAD

**Issue by alamgirqazi** [mdbootstrap/perfect-scrollbar#907]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/mdbootstrap/perfect-scrollbar/wiki/FAQ) and [Caveats](https://github.com/mdbootstrap/perfect-scrollbar/wiki/Caveats)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - [perfect-scrollbar JSFiddle](https://jsfiddle.net/utatti/dyvL31r6/)
- [ ] Provide a page or source code where the issue can be checked

I will update these above later.

I'm using ngx-perfect-scrollbar (https://www.npmjs.com/package/ngx-perfect-scrollbar) which uses perfect-scrollbar ^1.4.0

New npm install installs 1.5.0 version which shows scroller by default even though it shouldn't. It always has ps--active-y class added by default and it gets removed once you scroll even a little.

**Comment by alamgirqazi** [comment]
for now, I've set up a fork (https://www.npmjs.com/package/al-ngx-perfect-scrollbar) which fixes this issue. It uses only 1.4.0 perfect-scrollbar. 

If you use this, you only need to change the import in module.ts

```yarn add al-ngx-perfect-scrollbar@9.2.0```

or 

```yarn add al-ngx-perfect-scrollbar@9.2.0```

e.g 

replace 

```
import {
  PERFECT_SCROLLBAR_CONFIG,
  PerfectScrollbarConfigInterface,
  PerfectScrollbarModule
} from 'ngx-perfect-scrollbar';
```

with 

```
import {
  PERFECT_SCROLLBAR_CONFIG,
  PerfectScrollbarConfigInterface,
  PerfectScrollbarModule
} from 'al-ngx-perfect-scrollbar';

```

**Comment by mattonit** [comment]
Can you point us why 1.5.0 breaks the design? What exactly is broken and what can we do to fix it up?

**Comment by alamgirqazi** [comment]
A bit hard to replicate. I was also using custom css and maybe that was breaking it.

What was happening was that the scroller was displayed even though it shouldn't and when you scroll, it got removed. the ps--active-y class got removed once you scrolled.
