### ISSUE TITLE
destroy and reinitialize in Vue

### ISSUE THREAD

**Issue by Nakultanta** [mdbootstrap/perfect-scrollbar#957]
I have added this in my vue project and am unable to find any thing regarding destroy and reinitializing perfectscrollbar from the mounted.

here is the code i have written.

       mounted: function() {
                           let test = document.querySelectorAll(".focusList");
            test.forEach(x => {
                x.addEventListener('mouseover', () => {
                    let randomizerScrollbar = this.$refs.scrollbar.ps;
                    randomizerScrollbar.destroy();
                    randomizerScrollbar = null;
                });
                x.addEventListener('mouseout', () => {
                    let randomizerScrollbar = this.$refs.scrollbar.ps;
                    VuePerfectScrollbar();

                });
            })
       }
}

ERROR:  Uncaught TypeError: vue_perfect_scrollbar__WEBPACK_IMPORTED_MODULE_2___default(...) is not a function

I just want to simply stop/freeze perfectscrollbar when i have my mouseover div( these also contains perfect scrollbar).

**Comment by mercs600** [comment]
@Nakultanta just use this wrapper -> https://github.com/mercs600/vue2-perfect-scrollbar
