### ISSUE TITLE
scroll down infinitely still not fixed

### ISSUE THREAD

**Issue by exit-light** [mdbootstrap/perfect-scrollbar#982]
There is a problem similar to this:
**https://github.com/mdbootstrap/perfect-scrollbar/issues/951**
But I found a new reason:

```
function updateGeometry(i) {
  var element = i.element;
  var roundedScrollTop = Math.floor(element.scrollTop);
  var rect = element.getBoundingClientRect();

  i.containerWidth = Math.ceil(rect.width);
  i.containerHeight = Math.ceil(rect.height);
```
Example 'rect.height' == 298, i got infinite scroll.
But if I decrease the width by 1 from 'rect' here:
`i.containerHeight = Math.ceil(rect.height) - 1;` //297
then it will fixed.

By the way, in last fix (**which is defective in /dist**), when Math.ceil replaced on Math.round **https://github.com/mdbootstrap/perfect-scrollbar/commit/daeeddf5972c44a960f1d244a4b9719cb7c3d0b7**
the problem is solved if 'rect.height' is not an integer (531.4px) and rounded to 531. But not working if 'rect.height' 531.5 - 531.9 or if integer.

I think in 'i.containerHeight' necessary decrease value from 'rect.height' by 1, and it will fixed.

Have ideas?

**Comment by gonzalo-lorieto** [comment]
`"perfect-scrollbar": "npm:perfect-scrollbar-latest@1.5.2",` in your `package.json`

**Comment by exit-light** [comment]
> `"perfect-scrollbar": "npm:perfect-scrollbar-latest@1.5.2",` in your `package.json`

worked. Thanks)
